"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const home = fs.readFileSync(path.join(root, "index.html"), "utf8");
const quiz = fs.readFileSync(path.join(root, "health-lifestyle-quiz.html"), "utf8");
const start = fs.readFileSync(path.join(root, "intro.html"), "utf8");
const config = fs.readFileSync(path.join(root, "start-config.js"), "utf8");
const resources = fs.readFileSync(path.join(root, "resources", "index.html"), "utf8");
const circadian = fs.readFileSync(path.join(root, "resources", "circadian-rhythm", "index.html"), "utf8");
const cleanStart = start.toLowerCase();

assert.ok(home.includes('href="intro/"'), "homepage should route into the owned intro path");
assert.ok(quiz.includes('href="intro/"'), "quiz should route into the owned intro path");
assert.ok(home.includes('autoplay muted loop playsinline'), "homepage backflip video should autoplay silently in a loop");
assert.equal(home.includes('id="video-control"'), false, "homepage should have no pause/play control (2026-07-23 Heathrow call)");
assert.equal(start.includes('id="motion-control"'), false, "/start should have no pause/play control (2026-07-23 Heathrow call)");
assert.ok(home.includes('aria-hidden="true"'), "testimonial dialog should start outside the accessibility tree");
assert.ok(start.includes("60-minute Intro Call"), "start page should state the 60-minute offer");
assert.ok(start.includes("<strong>$79</strong>"), "start page should disclose the price before payment");
assert.ok(start.includes("Pay, then book"), "start page should state the order of operations");
assert.ok(start.includes("personalized written recap"), "start page should explain the post-call deliverable");
assert.ok(start.includes('src="media/intro-call-river-mobile.mp4"'), "start page should use the mobile PNW river hero video");
assert.equal(cleanStart.includes("heathrow"), false, "Heathrow's story should remain on the testimonials page, not /start");
assert.equal(cleanStart.includes("backflip.mp4"), false, "the Intro Call page should not reuse the performance-focused backflip hero");
assert.equal(cleanStart.includes("discovery session"), false, "old Discovery Session language must be removed");
assert.equal(cleanStart.includes("baggage unpacking"), false, "old Baggage Unpacking language must be removed");
assert.equal(cleanStart.includes("45-minute"), false, "old 45-minute duration must be removed");
assert.equal(cleanStart.includes("free clarity"), false, "free-call language must be removed");
assert.equal(start.includes("resource-exit"), false, "the not-sure resource exit is removed — /intro ends on the paid path (2026-07-23 Heathrow call)");
assert.equal(cleanStart.includes("if you are not sure yet"), false, "no hedge copy on /intro");
assert.equal(start.includes("Review the Intro Call"), false, "the bottom of the page should not repeat the Intro Call CTA");
assert.equal(resources.includes("calendly.com"), false, "the resources page should not restore the old free booking path");
assert.ok(resources.includes('href="../intro.html#intro-call"'), "the resources page should return personalized visitors to the paid Intro Call");
assert.equal(circadian.toLowerCase().includes("free clarity"), false, "the Circadian resource should not offer a free call");
assert.ok(circadian.includes('href="../../intro.html#intro-call"'), "the Circadian resource should return personalized visitors to the paid Intro Call");
assert.equal(config.includes('paymentUrl: ""'), true, "production payment link must remain visibly unconfigured until Justin supplies it");
assert.ok(/bookingUrl: "(|https:\/\/calendly\.com\/justin-the-practice\/[a-z0-9-]+)"/.test(config), "founding-period booking link must be empty or Justin's own Calendly event");
assert.ok(start.includes('candidate.hostname === "buy.stripe.com"'), "checkout should accept only Stripe-hosted Payment Links");
assert.ok(start.includes('candidate.hostname === "calendly.com"'), "founding-period booking should accept only Calendly-hosted links");
assert.ok(start.includes('id="booking-modal"'), "founding-period booking sheet must exist for the no-payment demo flow");
assert.equal(start.includes('type="card"') || start.toLowerCase().includes("card number"), false, "the booking sheet must never collect card details");
assert.ok(start.includes("Book now, pay nothing today"), "the booking sheet states plainly that no payment is taken");
assert.ok(fs.existsSync(path.join(root, "intro", "index.html")), "the QR-compatible /intro route should exist");
assert.ok(fs.readFileSync(path.join(root, "start", "index.html"), "utf8").includes("../intro.html"), "old /start route must redirect to /intro");
assert.ok(fs.readFileSync(path.join(root, "start.html"), "utf8").includes("intro.html"), "old start.html must redirect to intro.html");

process.stdout.write("✓ paid Intro Call path is internally consistent and safely staged\n");
